"""initial schema

Revision ID: c51e59a870dc
Revises: 
Create Date: 2026-10-05 14:07:16.529124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51e59a870dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'sem', 'swe', 'ssm', 'directeur_campus', 'directeur_technique', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'invited', 'disabled', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('backups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('format', sa.Enum('sql', 'csv', name='backup_format'), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_triggered_by'), 'backups', ['triggered_by'], unique=False)
    op.create_table('camps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='camp_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_camps_dates'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camps_organizer_id'), 'camps', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_camps_slug'), 'camps', ['slug'], unique=True)
    op.create_index(op.f('ix_camps_status'), 'camps', ['status'], unique=False)
    op.create_table('camp_modalities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camp_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('age_restriction', 'education_level', 'other', name='modality_type'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camp_modalities_camp_id'), 'camp_modalities', ['camp_id'], unique=False)
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camp_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('hotline', 'chatbot', name='contact_channel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_camp_id'), 'contact_messages', ['camp_id'], unique=False)
    op.create_table('landing_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camp_id', sa.UUID(), nullable=False),
    sa.Column('season_theme', sa.Enum('printemps', 'ete', 'automne', 'hiver', name='season_theme'), nullable=False),
    sa.Column('hero_title', sa.String(length=200), nullable=True),
    sa.Column('hero_description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camp_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camp_id'], ['camps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrations_camp_id'), 'registrations', ['camp_id'], unique=False)
    op.create_index(op.f('ix_registrations_email'), 'registrations', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrations_email'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_camp_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_table('landing_pages')
    op.drop_index(op.f('ix_contact_messages_camp_id'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_camp_modalities_camp_id'), table_name='camp_modalities')
    op.drop_table('camp_modalities')
    op.drop_index(op.f('ix_camps_status'), table_name='camps')
    op.drop_index(op.f('ix_camps_slug'), table_name='camps')
    op.drop_index(op.f('ix_camps_organizer_id'), table_name='camps')
    op.drop_table('camps')
    op.drop_index(op.f('ix_backups_triggered_by'), table_name='backups')
    op.drop_table('backups')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Les types ENUM PostgreSQL ne sont pas supprimés automatiquement par
    # op.drop_table() (contrairement à Base.metadata.drop_all()). Sans ce
    # bloc, un downgrade suivi d'un upgrade échoue avec
    # "type ... already exists".
    for enum_name in (
        "user_role", "user_status", "camp_status", "modality_type",
        "contact_channel", "season_theme", "backup_format",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
